### PR TITLE
round robin CPU scheduling

### PR DESCRIPTION
**Pull request by sneha2180**

### CODE REVIEW

**Comment by hitaarthh** [comment]
Good work @sneha2180 saw your profile, and in case you are interested in REACT JS development, contact me in case you are interested and looking into creating some projects.

**Comment by sneha2180** [comment]
y is it still not accepted by hacktober fest ???

**Comment by sneha2180** [comment]
yes I m interested to study React Js

**Comment by hitaarthh** [comment]
> yes I m interested to study React Js
@sneha2180 You can find my contact through my [website](https://hitaarthh.github.io/).

**Comment by hitaarthh** [comment]
> y is it still not accepted by hacktoberfest ???

takes 15 mins to update, it should update soon.

**Pull request merged**
