### PR TITLE
Create fcfs.c

### PR DESCRIPTION
**Pull request by FaiyazUllah786**

### CODE REVIEW

**Comment by hitaarthh** [comment]
What does this program deals with?

**Comment by FaiyazUllah786** [comment]
Scheduling algorithm of operating system

**Comment by hitaarthh** [comment]
Can you elaborate on it in through comments in the code and the make a PR?

**Comment by FaiyazUllah786** [comment]
Got it, thanks!

**Comment by FaiyazUllah786** [comment]
I have did some extra line of comments in code.kindly check it.

**Pull request merged**
